/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Transactiontype = "EXPENSE" | "INCOME";

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Category {
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  type: Transactiontype;
  updatedAt: Timestamp;
}

export interface Transaction {
  amount: Numeric;
  categoryId: string;
  createdAt: Generated<Timestamp>;
  date: Generated<Timestamp>;
  description: string | null;
  id: string;
  transferGroupId: string | null;
  updatedAt: Timestamp;
  walletId: string;
}

export interface Wallet {
  balance: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  id: string;
  name: string;
  updatedAt: Timestamp;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  Category: Category;
  Transaction: Transaction;
  Wallet: Wallet;
}
